# Generated by Django 4.1.1 on 2022-10-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('due_date', models.DateField()),
                ('order', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
